### ISSUE TITLE
multithreading in avisynth

### ISSUE THREAD

**Issue by amayra** [gdiaz384/frameTools#1]
can i make FrameTools filters to be run multithreaded to speed up processing ?

**Comment by gdiaz384** [comment]
frameTools.avsi is actually just an easy to use frontend for avisynth's native FreezeFrame(), trim() and concatenate (+,++) functions. Internally, it also uses Apply() and Eval() to operate. 

As long as the internal functions are themselves multi-threaded, the front-end functions like sceneFilter() and fixframe, ff(), should be multi-threaded as well without having to do anything specifically. 

That said, because it uses the internal functions, if they are not multi-threaded, then support cannot be added because such a change would need to occur at the base-code level rather than at the avsi level.

For merge fix frame, mff(), check out the [Bad Frames.dll Documentation](http://avisynth.org.ru/badframes/badframes.html).
